# LU and PLU factorization

In [1]:
import numpy as np
import scipy as sp

## LU factorization

In [2]:
def lu(A):
    """Compute the LU factorization of a matrix A."""
    n = len(A)
    L = np.identity(n)
    U = np.copy(A)

    for k in range(n-1):
        for i in range(k+1, n):
            L[i, k] = U[i, k] / U[k, k]
            for j in range(k+1, n):
                U[i, j] -= L[i, k] * U[k, j]
    
    return L, np.triu(U)

**Example**

$$A = \begin{bmatrix} 2 & 1 & 1 & 0 \\ 4 & 3 & 3 & 1 \\ 8 & 7 & 9 & 5 \\ 6 & 7 & 9 & 8 \end{bmatrix}.$$

In [3]:
A = np.array([[2, 1, 1, 0],
              [4, 3, 3, 1],
              [8, 7, 9, 5],
              [6, 7, 9, 8]])

L, U = lu(A)

print("L = \n{}\n".format(L))
print("U = \n{}\n".format(U))

L = 
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]

U = 
[[2 1 1 0]
 [0 1 1 1]
 [0 0 2 2]
 [0 0 0 2]]



In [4]:
x_exact = np.random.rand(4)
b = A @ x_exact

print("x_exact = \n{}".format(x_exact))

x_exact = 
[0.30197021 0.26671882 0.82932261 0.71022832]


In [5]:
y = sp.linalg.solve_triangular(L, b, lower=True)
x = sp.linalg.solve_triangular(U, y)

print("x = \n{}".format(x_exact))

x = 
[0.30197021 0.26671882 0.82932261 0.71022832]


## PLU factorization

**Example**

$$A = \begin{bmatrix} 0 & 0 & -1 & 1 \\ 1 & 1 & -1 & 2 \\ -1 & 1 & 2 & 0 \\ 1 & 2 & 0 & 2 \end{bmatrix}.$$

In [6]:
A = np.array([[0, 0, -1, 1],
              [1, 1, -1, 2],
              [-1, 1, 2, 0],
              [1, 2, 0, 2]])

PT, L, U = sp.linalg.lu(A)
P = PT.T

print("P = \n{}\n".format(P))
print("L = \n{}\n".format(L))
print("U = \n{}\n".format(U))

P = 
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]

L = 
[[ 1.   0.   0.   0. ]
 [-1.   1.   0.   0. ]
 [ 0.   0.   1.   0. ]
 [ 1.   0.5 -0.5  1. ]]

U = 
[[ 1.   1.  -1.   2. ]
 [ 0.   2.   1.   2. ]
 [ 0.   0.  -1.   1. ]
 [ 0.   0.   0.  -0.5]]



In [7]:
L, U = lu(P @ A)

print("L = \n{}\n".format(L))
print("U = \n{}\n".format(U))

L = 
[[ 1.   0.   0.   0. ]
 [-1.   1.   0.   0. ]
 [ 0.   0.   1.   0. ]
 [ 1.   0.5 -0.5  1. ]]

U = 
[[ 1.   1.  -1.   2. ]
 [ 0.   2.   1.   2. ]
 [ 0.   0.  -1.   1. ]
 [ 0.   0.   0.  -0.5]]



In [8]:
x_exact = np.random.rand(4)
b = A @ x_exact

print("x_exact = \n{}".format(x_exact))

x_exact = 
[0.34083438 0.35890783 0.17666278 0.02253948]


In [9]:
y = sp.linalg.solve_triangular(L, P @ b, lower=True)
x = sp.linalg.solve_triangular(U, y)

print("x = \n{}".format(x_exact))

x = 
[0.34083438 0.35890783 0.17666278 0.02253948]


### Space-efficient PLU factorization

In [10]:
LU, piv = sp.linalg.lu_factor(A)

print("Combined L and U: \n{}\n".format(LU))
print("Pivot (interchange) vector: \n{}\n".format(piv))

Combined L and U: 
[[ 1.   1.  -1.   2. ]
 [-1.   2.   1.   2. ]
 [ 0.   0.  -1.   1. ]
 [ 1.   0.5 -0.5 -0.5]]

Pivot (interchange) vector: 
[1 2 2 3]



In [11]:
def pivot_to_permutation(piv):
    perm = np.arange(len(piv))
    
    for i in range(len(piv)):
        perm[i], perm[piv[i]] = perm[piv[i]], perm[i]
        
    return perm

In [12]:
perm = pivot_to_permutation(piv)

print("Permutation vector: \n{}\n".format(perm))
print("PA: \n{}\n".format(P @ A))
print("Permuted A: \n{}\n".format(A[perm, :]))

Permutation vector: 
[1 2 0 3]

PA: 
[[ 1.  1. -1.  2.]
 [-1.  1.  2.  0.]
 [ 0.  0. -1.  1.]
 [ 1.  2.  0.  2.]]

Permuted A: 
[[ 1  1 -1  2]
 [-1  1  2  0]
 [ 0  0 -1  1]
 [ 1  2  0  2]]

